ISW_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
#from apps.sf.views import index
urlpatterns = [
    path('sf/', include('apps.sf.urls')),
    path('users/', include('apps.users.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='sf/index.html',redirect_authenticated_user= True), name="login"),
    path('', LogoutView.as_view(), name="logout")
]

apps/users/urls.py
'''URLS'''
from django.urls import path

from apps.users import views
from django.contrib.auth.decorators import login_required
app_name = 'users'
urlpatterns = [
    path('registrar/', views.RegisterView.as_view(), name='registrar'),
    path('publication_form/', login_required(views.publication_new), name='new_publication'),
    path('publication_list/', login_required(views.publication_list), name='list_publication'),
    path('publication_edit/<int:id_publication>/', login_required(views.publication_edit), name='edit_publication'),
    path('publication/<int:id_publication>/', login_required(views.publication_show), name='publication'),
    path('publication_delete/<int:id_publication>/', login_required(views.publication_delete), name='delete_publication'),
    path('perfil/<username>/', login_required(views.get_user_profile), name='get_user_profile'),
    path('index/',login_required(views.user_index),name='user_index'),
    path('postularse/<int:id_publication>/',login_required(views.postularse),name='postularse'),
    path('aceptar_rechazar/<int:id_publication>/<username>/<value>/',login_required(views.aceptar_rechazar),name='aceptar_rechazar'),
    path('contract_form/<int:id_publication>/<username>/', login_required(views.contract_new), name='new_contract'),
    path('contract_show/<int:id_publication>/<username>/', login_required(views.contract_show), name='show_contract'),
    path('contract_sign/<int:id_contrato>/<username>/<value>/', login_required(views.contract_client_sign), name='sign_contract'),
    path('terminosycondiciones/', views.terminosycondiciones, name='terminosycondiciones'),

]

templates/base/base.html
{% load staticfiles%}
<!DOCTYPE html>
<html lang="en">

{% block header %}
  <!-- Fonts -->
  <head>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="{% static 'vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <!-- Argon CSS -->
    <link type="text/css" href="{% static 'css/argon.css' %}" rel="stylesheet">
    

  </head>
  <div class="main-content">
    <!-- Top navbar -->
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
      <div class="container-fluid">
        <!-- Brand -->
       
        
        {%if type_of_user == "C"%} 
          Secure Freelancer 
        {%else%}          
          <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="{% url 'users:user_index'%}">Secure Freelancer</a>
        {%endif%}


        <!-- Form -->
        <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
          <div class="form-group mb-0">
            <div class="input-group input-group-alternative">
              <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-search"></i></span>
              </div>
              <input class="form-control" placeholder="Search" type="text">
            </div>
          </div>
        </form>
        <!-- User -->
        <ul class="navbar-nav align-items-center d-none d-md-flex">
          <li class="nav-item dropdown">
            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                  {%if current_user.username == "Ronaldinho"%}
                  <img alt="Image placeholder" src="{% static 'img/theme/r10.png' %}">
                  {%elif current_user.username == "Capitan_America"%}
                  <img alt="Image placeholder" src="{% static 'img/theme/cap.jpeg' %}">
                  {%else%}
                  <img alt="Image placeholder" src="{% static 'img/theme/personal-user-illustration-@2x.png' %}">
                  {%endif%}
                </span>
                <div class="media-body ml-2 d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold">{{current_user.username}}</span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
              
              <a href="/users/perfil/{{ current_user.username }}/" class="dropdown-item">
                <i class="ni ni-single-02"></i>
                <span>My profile</span>
              </a>
              
              <a href="../examples/profile.html" class="dropdown-item">
                <i class="ni ni-email-83"></i>
                <span>Messages</span>
              </a>
              
              <div class="dropdown-divider"></div>
              <a href="{% url 'logout' %}">
                <i class="ni ni-user-run"></i>
                <span>Logout</span>
              </a>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </div>
{% endblock %}


{% block content %}
<body>


</body>
{% endblock %}

{%block footer%}
<footer></footer>
 <!-- Argon Scripts -->
  <!-- Core -->
  <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Argon JS -->
  <script src="{% static 'js/argon.js' %}"></script>
{% endblock %}



</html>