ISW_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
#from apps.sf.views import index
urlpatterns = [
    path('sf/', include('apps.sf.urls')),
    path('users/', include('apps.users.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='sf/index.html',redirect_authenticated_user= True), name="login"),
    path('', LogoutView.as_view(), name="logout")
]

apps/users/urls.py
'''URLS'''
from django.urls import path

from apps.users import views
from django.contrib.auth.decorators import login_required
app_name = 'users'
urlpatterns = [
    path('registrar/', views.RegisterView.as_view(), name='registrar'),
    path('publication_form/', login_required(views.publication_new), name='new_publication'),
    path('publication_list/', login_required(views.publication_list), name='list_publication'),
    path('publication_edit/<int:id_publication>/', login_required(views.publication_edit), name='edit_publication'),
    path('publication/<int:id_publication>/', login_required(views.publication_show), name='publication'),
    path('publication_delete/<int:id_publication>/', login_required(views.publication_delete), name='delete_publication'),
    path('perfil/<username>/', login_required(views.get_user_profile), name='get_user_profile'),
    path('index/',login_required(views.user_index),name='user_index'),
    path('postularse/<int:id_publication>/',login_required(views.postularse),name='postularse'),
    path('aceptar_rechazar/<int:id_publication>/<username>/<value>/',login_required(views.aceptar_rechazar),name='aceptar_rechazar'),
    path('contract_form/<int:id_publication>/<username>/', login_required(views.contract_new), name='new_contract'),
    path('contract_show/<int:id_publication>/<username>/', login_required(views.contract_show), name='show_contract'),
    path('contract_sign/<int:id_contrato>/<username>/<value>/', login_required(views.contract_client_sign), name='sign_contract'),
    path('terminosycondiciones/', views.terminosycondiciones, name='terminosycondiciones'),

]

apps/users/forms.py
'''forms'''
from django import forms
from apps.users.models import Publication
from apps.users.models import User
from apps.users.models import Contract
from apps.users.models import generate_RSA
from django.contrib.auth import authenticate, login
class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication

        fields = [
            'name',
            'overview',
            'budget',
            'skills',
        ]
        labels = {
            'name' : 'Nombre',
            'overview' : 'Descripción',
            'budget' : 'Presupuesto',
            'skills' : 'Habilidades requeridas',
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control '}),
            'overview' : forms.TextInput(attrs={'class':'form-control'}),
            'budget' : forms.Select(attrs={'class':'form-control'}),
            'skills' : forms.CheckboxSelectMultiple(),
        }

class ContractForm(forms.ModelForm):
    '''delivery = forms.DateTimeField(label="Fecha de entrega",
        input_formats=['%Y/%m/%d'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        })
    )'''
    class Meta:
        model = Contract

        fields = [
            'delivery',
            'payment',
        ]
        labels = {
            'delivery' : 'Fecha de entrega',
            'payment' : 'Pago',
        }
        widgets = {
            'Fecha de entrega' : forms.DateInput(attrs={'class':'form-control'}),
            'Pago' : forms.NumberInput(attrs={'class':'form-control'}),
        }


class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control '}))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'class':'form-control '}))

    class Meta:
        model = User
        fields = ('username', 'email','type_of_user','first_name','last_name','address','city','country','postal_code','birthday') #'full_name',)
        labels = {
            'username' : 'Nombre de usuario',
            'email': 'Email',
            'type_of_user': 'Tipo de usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'address' : 'Direccion',
            'city' : 'Ciudad',
            'country': 'Pais',
            'postal_code': 'Codigo Postal',
            'birthday': 'Fecha de nacimiento',
            'education': 'Educacion',
            'about_me': 'Sobre mi',
            'degree': 'Carrera'
        }
        
        widgets = {
            'username' : forms.TextInput(attrs={'class':'form-control '}),
            'email' : forms.EmailInput(attrs={'class':'form-control'}),
            'type_of_user' : forms.Select(attrs={'class':'form-control '}),
            'first_name' : forms.TextInput(attrs={'class':'form-control '}),
            'last_name' : forms.TextInput(attrs={'class':'form-control '}),
            'address' : forms.TextInput(attrs={'class':'form-control '}),
            'city' : forms.TextInput(attrs={'class':'form-control'}),
            'country' : forms.TextInput(attrs={'class':'form-control'}),
            'birthday': forms.DateInput(attrs={'class' : 'form-control'}), 
            'education': forms.TextInput(attrs={'class':'form-control'}),
            'degree': forms.TextInput(attrs={'class':'form-control'}),
            'about_me': forms.TextInput(attrs={'class':'form-control'})
        }
        

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.active = True # send confirmation email
        keys = generate_RSA()
        user.public_key = keys[1]
        user.private_key = keys[0]
        if commit:
            user.save()
        return user

apps/users/views.py
'''vistas Usuarios '''
#from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.http import HttpResponse
from django.shortcuts import redirect, render
from apps.users.forms import PublicationForm
from apps.users.forms import ContractForm
from apps.users.models import Publication
from apps.users.models import User
from apps.users.models import Postulados
from apps.users.models import Contract
from apps.users.forms import RegisterForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from apps.users.models import sign_data
# Create your views here.
from django.http import HttpResponseRedirect

from base64 import b64encode, b64decode
from Crypto.Signature import PKCS1_v1_5
      
class RegisterView(CreateView):
   form_class = RegisterForm
   
   template_name = 'users/registrar.html'
   success_url = reverse_lazy('users:user_index')
   
   
   def form_valid(self,form_class):
      username = self.request.POST['username']
      password = self.request.POST['password1']
      user = form_class.save()
      #new_user = authenticate(username=username,password=password)
      login(self.request,user)
      return HttpResponseRedirect(self.success_url)

def get_user_profile(request,username):
   #current_user = User.objects.get(username=request.user.username)
   age = request.user.get_age()
   if request.user.type_of_user == 'C':
      publications = Publication.objects.filter(user_id = request.user.id)
  
      context = {
        'current_user': request.user,
        'publications':publications,
        'age': age,
        }
      return render(request, 'users/ClientProfile.html',context)
   else:
      print("----------->" + str(request.user.id))
      publications = Publication.objects.filter(freelancer_id = request.user.id)
      context = {
        'current_user': request.user,
        'publications':publications,
        'age': age,
        }
      return render(request,'users/FreelancerProfile.html', context)       

def user_index(request):
   age = request.user.get_age()
   publications = Publication.objects.all()
   publications_client = Publication.objects.filter(user_id = request.user.id)
   current_user = request.user
   #aux = Auxiliar()
   for p in publications:
          name_user = User.objects.get(pk=p.user_id)
          p.user_id = name_user
          
   context = {
      'current_user': current_user,
      'publications': publications,
      'aux': Auxiliar,
      'age': age,
   }
   if request.user.type_of_user == "F":
     
      print("ES FREELANCER")
      return render(request,'users/userIndex.html',context)
   else:
      context["publications"] = publications_client
      print("ES CLIENTE")
      return render(request, 'users/ClientProfile.html',context)
          
class Auxiliar(object):
      def get_user(self,id_u):
            return User.objects.filter(id = id_u)

def postularse(request,id_publication):
      #print(request.POST.get('id_publicatio '))
      print("------------>"+str(id_publication))
      print("------------>" + request.user.username)
      new_postulado = Postulados(user_id = request.user.id,publication_id = id_publication)
      p = Postulados.objects.filter(user_id = request.user.id, publication_id = id_publication)
      print(p);
      context = {
         'current_user': request.user,
         'publication': id_publication,
         'error': len(p),
      } 
      if len(p) > 0:
         return render(request,"users/postularse.html",context)
      else:
         new_postulado.save()
         return render(request,"users/postularse.html",context)

def aceptar_rechazar(request,id_publication,username,value):
       print(value)
       postulados = Postulados.objects.filter(publication_id = id_publication)
       user_postulado = User.objects.get(username = username)
       print(user_postulado.id)
       if value == 'aceptado':
              for p in postulados:
                     if(p.user_id != user_postulado.id):
                        p.state = "rechazado"
                        p.save()
                     
                     else:
                            p.state = "aceptado" 
                            p.save()
       elif value == 'rechazado':
         user_postulado = Postulados.objects.get(user_id = user_postulado.id,publication_id = id_publication)
         print(user_postulado)
         user_postulado.state = "rechazado"
         user_postulado.save()

       context = {
          'current_user':request.user,
          'publication': id_publication,
          'postulado': username,
          'state': value,
       }
       return render(request,"users/aceptar_rechazar.html",context)
      

def publication_show(request,id_publication):   
   publication = Publication.objects.get(pk=id_publication)
   publication.user_id = User.objects.get(pk = publication.user_id)
   skills = publication.skills.filter(publication=id_publication)
   postulados = Postulados.objects.filter(publication_id = id_publication)
   accepted = Postulados.objects.filter(publication_id = id_publication,state = "aceptado")
   flag = False
   if len(accepted) > 0:
      flag = True
   
   print("------------")
   print(accepted)
   for p in postulados:
      username = User.objects.get(pk=p.user_id)
      p.user_id = username.username
   #print(skills[0].name)

   context = {
      'current_user': request.user,
      'publication': publication,
      'skills':skills,
      'postulados': postulados,
      'flag': flag

   } 
   return render(request,'users/publication.html', context) 

def contract_client_sign(request, id_contrato,username,value):
       context = {
          'current_user' : request.user
       }
       contrato = Contract.objects.get(id = id_contrato)
       texto = (str(contrato.delivery) + str(contrato.payment)).encode()
       publication = Publication.objects.get(id = contrato.publication_id)
       cliente = User.objects.get(id = contrato.client_id)
       if value=="aceptar":
              contrato.id_freelancer = request.user.id
              #contrato.freelancer_signature = sign_data(request.user.private_key.encode(),b64encode(texto))
              contrato.freelancer_signature = sign_data(request.user.private_key.encode(),b64encode(texto)).decode()
              contrato.save()
              publication.freelancer_id = request.user.id
              publication.save()
      
       return render(request,'users/contract_signed.html', context)
       
def publication_new(request):
   context = {}
   #context['current_user'] = request.user
   if request.method == 'POST':
      form = PublicationForm(request.POST)
      context['form'] = form
      if form.is_valid():
         np = form.save(commit=False)
         np.user_id = request.user.id
         skills = request.POST.getlist('skills')
         print(skills)
         np.save()
         for i in skills:
            np.skills.add(i)    
      return HttpResponseRedirect(reverse('users:get_user_profile',kwargs={'username':request.user.username}))
   else:
      form = PublicationForm()
   return render(request,'users/publication_form.html/',{'form':form,'current_user':request.user})

def contract_new(request,id_publication,username):
      context = {}
      user_postulado = User.objects.get(username = username)
      publication = Publication.objects.get(id = id_publication)
      if request.method == 'POST':
         form = ContractForm(request.POST)
         context['form'] = form
         if form.is_valid():
            n = form.save(commit=False)
            texto = (str(n.delivery) + str(n.payment)).encode()
            #print(type(request.user.private_key))
            n.client_signature = sign_data(request.user.private_key.encode(),b64encode(texto)).decode()
            print(n.client_signature)
            n.client_id = request.user.id
            n.freelancer_id = user_postulado.id
            n.publication_id = id_publication
            n.save()
         return HttpResponseRedirect(reverse('users:get_user_profile',kwargs={'username':request.user.username}))
      else:
         form = ContractForm()
         for field in form:
                print(field.label_tag())
         context = {
            'form':form,
            'current_user':request.user,
            'd':field.label_tag(),
            'publication' : publication,

         }
      return render(request,'users/contract_form.html/',context)

def contract_show(request,id_publication,username):
       user_postulado = User.objects.get(username = username)
       publication = Publication.objects.get(id = id_publication)
       try:
          contrato = Contract.objects.get(publication_id = id_publication)
          client = User.objects.get(id=contrato.client_id)
          c = True
          context = {
          'contrato' : contrato,
          'publication':publication,
          'current_user':request.user,
          'client':client,
          'c' : c,
          }
       except Contract.DoesNotExist:
          contrato = None
          c = False   
          context = {
          'publication':publication,
          'current_user':request.user,
          'c':c,
          }    
       
       
       return render(request,'users/contract_show.html/',context)

def publication_list(request):
   publications = Publication.object.all()
   context =   {'publications':publications}
   return render(request, 'publicaciones/publicaciones_list.html', context)

def publication_edit(request,id_Publication):
   publication = Publication.object.get(id=id_Publication)
   if request.method == 'GET':
      form = PublicationForm()  
   else:
      form = PublicationForm(request.POST,instance=publication)
      if form.is_valid():
         form.save()
      return redirect('users:list_publication')
   return render(request,'users/publication_form.html',{'form':form})

templates/users/ClientProfile.html
{% extends 'base/base.html' %}
{% load staticfiles%}


<!----{% for publication in publications %}
    <h1>{{publication.name}}</h1>
{% endfor %} -->




{%block content%}
<body>
     <!-- Main content -->
  <div class="main-content">
      
        <!-- Header -->
        
        <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 600px; background-image: url({% static 'img/theme/photo-1550745165-9bc0b252726f.jpeg'%}); background-size: cover; background-position: center top;">
          <!-- Mask -->
          <span class="mask bg-gradient-default opacity-8"></span>
          <!-- Header container -->
          <div class="container-fluid d-flex align-items-center">
            <div class="row">
              <div class="col-lg-7 col-md-10">
                <h1 class="display-2 text-white">Hello {{current_user.username}}</h1>
                <p class="text-white mt-0 mb-5">Este es tu perfil de usuario, aquí podrás ver tu información y el avance de tus proyectos</p>
                <a href="#!" class="btn btn-info">Edit profile</a>
              </div>
            </div>
          </div>
        </div>
        <!-- Page content -->
        <div class="container-fluid mt--7">
          <div class="row">
            <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
              <div class="card card-profile shadow">
                <div class="row justify-content-center">
                  <div class="col-lg-3 order-lg-2">
                    <div class="card-profile-image">
                      <a href="#">
                        {%if current_user.username == "Ronaldinho"%}
                        <img src="{% static 'img/theme/r10.png' %}" class="rounded-circle">
                        {%else%}
                        <img src="{% static 'img/theme/personal-user-illustration-@2x.png' %}" class="rounded-circle">
                        {%endif%}
                      </a>
                    </div>
                  </div>
                </div>
                <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
                  <div class="d-flex justify-content-between">
                    <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
                    <a href="#" class="btn btn-sm btn-default float-right">Message</a>
                  </div>
                </div>
                <div class="card-body pt-0 pt-md-4">
                  <div class="row">
                    <div class="col">
                      <div class="card-profile-stats d-flex justify-content-center mt-md-5">
                        <div>
                          {%for i in "x"|ljust:current_user.calification%}
                            <label for="radio1">★</label>
                          {%endfor%}

                        </div>
                        
                      </div>
                    </div>
                  </div>
                  <div class="text-center">
                    <h3>
                      {{current_user.username}}<span class="font-weight-light">, {{age}}</span>
                    </h3>
                    <div class="h5 font-weight-300">
                      <i class="ni location_pin mr-2"></i>{{current_user.city}} , {{current_user.country}}
                    </div>
                    <div class="h5 mt-4">
                      <i class="ni business_briefcase-24 mr-2"></i>{{current_user.degree}}
                    </div>
                    <div>
                      <i class="ni education_hat mr-2"></i>{{current_user.education}}
                    </div>
                    <hr class="my-4" />
                    <p>{{current_user.about_me}}</p>
                    
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-8 order-xl-1">
              <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                  <div class="row align-items-center">
                    <div class="col-8">
                      <h3 class="mb-0">Proyectos actuales</h3>
                    </div>
                    <div class="col-4 text-right">
                      <a href="{% url 'users:new_publication' %}" class="btn btn-sm btn-primary">Publicar</a>
                    </div>
                  </div>
                  <div class="table-responsive">
                      <table class="table align-items-center table-flush">
                          <thead class="thead-light">
                            <tr>
                              <th scope="col">Proyecto</th>
                              <th scope="col">Freelancer</th>
                              <th scope="col">Avance</th>
                            </tr>
                          </thead>
                          <tbody>
                            
                            {% for p in publications %}
                            <tr>
                              <th scope="row">
                                {{p.name}}
                              </th>
                              <td>
                                {{p.freelancer}}
                              </td>
                              <td>
                                  <div class="d-flex align-items-center">
                                      <span class="mr-2">{{p.progress}} %</span>
                                      <div>
                                        <div class="progress">
                                          <div class="progress-bar bg-gradient-danger" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{p.progress}}%;"></div>
                                        </div>
                                      </div>
                                    </div>
                              </td>
                              <td>
                                <th> <a href="/users/publication/{{p.id}}/" class="btn btn-sm btn-primary">Ver</a> </th>
                              </td>
                            </tr>
                            {% endfor %}
                           
                            
                            
                          </tbody>
                        </table>
    
                  </div>
                </div>
                
              </div>
              <!--Skilss-->
               <!-- Projects table -->
              
               
            </div>
            
            
          </div>
          <!-- Footer -->
          <footer class="footer">
           
          </footer>
        </div>
      </div>
    
</body>

{%endblock%}

templates/users/aceptar_rechazar.html
{% extends 'base/base.html' %}
{% load staticfiles%}
 {%block content%}
 <body>
     <div class='main-content'>
        <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        </div>
            <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
                <div class="row justify-content-center">
                    <div class="col-lg-6 col-md-8">
                            <div class="card bg-secondary shadow border-0">
                                    <div class="card-header bg-transparent pb-5">
                                        <div class='text-center'>
                                               Has {{state}} a {{postulado}}
                                        </div>
                                        
                                    </div>
                            </div>
                    </div>
                </div>
            </div>

        
     </div>
    

 </body>


{%endblock%}

templates/users/publication.html
{% extends 'base/base.html' %}
{% load staticfiles%}
 


{% block content %}
<body>
    <div class="main-content">
        <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        </div>
        <div class="container-fluid mt--7">
          <div class="row mt-5">
              <div class="col-xl-8 mb-5 mb-xl-0">
                <div class="card bg-secondary shadow border-0">
                  <div class="card-header bg-transparent pb-5">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                          <img alt="Image placeholder" src="{% static 'img/theme/personal-user-illustration-@2x.png' %}">
                        </span>
                        <div class="media-body ml-2 d-none d-lg-block">
                          <span class="mb-4 text-sm  font-weight-bold">{{publication.user_id}}</span>
                        </div>
                        <div class="media-body ml-2 d-none d-lg-block">
                                <span class="mb-4 text-sm  font-weight-bold">{{publication.date}}</span>
                        </div>
                      </div>
        
                  </div>
                  <div class="card-body px-lg-5 py-lg-5">
                    <h1>Nombre: {{publication.name}}</h1>
                    <h1>Presupuesto: {{publication.budget}}</h1>
                    <h1>Descripción:  </h1>
                    <center><textarea disabled=true>{{publication.overview}}</textarea></center>
                    {%if current_user.type_of_user == 'F'%}
                    <center>
                        <form action="{% url 'users:postularse' publication.id %}" method='POST'>
                            {% csrf_token %}
                            
                            <button onclick ="myFunction()" class="btn btn-sm btn-primary" type='submit'>Postularse</button>

                        </form>
                    </center>
                    {%endif%}
                    <h1>Habilidades para este proyecto: <br/></h1>
                    {%for s in skills%}
                    <button type="button" class="btn btn-secondary">
                      {{s.name}}
                    </button>
                        
                    {%endfor%}
                  </div>
                </div>
              </div>
              <div class="col-xl-4">
                  <div class="card shadow">
                    <div class="card-header border-0">
                      <div class="row align-items-center">
                        <div class="col">
                          <h3 class="mb-0">Postulados</h3>
                        </div>
                      </div>
                    </div>
                    <div class="table-responsive">
                      <!-- Projects table -->
                      <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                          <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Fecha</th>
                            <th scope="col">Estado</th>
                          </tr>
                        </thead>
                        <tbody>
                          {%for p in postulados%}
                          <tr>
                            <th> {{p.user_id}}</th>
                            <th></th>
                            {%if current_user.type_of_user == 'F' %}
                            <th>{{p.state}}</th>
                              {%if current_user.username == p.user_id and flag == True%}
                              <th>
                                  <form action="{% url 'users:show_contract' publication.id current_user.username%}" method='POST'>
                                      {% csrf_token %}
                                      <button class="btn btn-primary" type='submit'>Acordar</button>
                                  </form>
                              </th>
                              {%endif%}
                              
                            {%else%}
                            {%if not flag %}
                              {%if p.state == "rechazado"%}
                                <th>rechazado</th>
                              {%else%}
                                      <th>
                                        
                                          {% with "aceptado" as a%}
                                          <form action="{% url 'users:aceptar_rechazar' publication.id p.user_id a%}" method='POST'>
                                              {% csrf_token %}
                                              <button class="btn btn-success" type='submit'>Aceptar</button>
                                            </form>
                                          {% endwith%}
                                          
                                        </th> 
                                        <th>
                                          {% with "rechazado" as n%}
                                          <form action="{% url 'users:aceptar_rechazar' publication.id p.user_id n%}" method='POST'>
                                            {% csrf_token %}
                                            <button class="btn btn-danger" type='submit'>Rechazar</button>
                                          </form>
                                          {% endwith%}
                                        </th> 
                                {%endif%}
                                        {%else%}
                                <th>{{p.state}}</th>
                                {%if p.state == "aceptado"%}
                                <th>
                                    <form action="{% url 'users:new_contract' publication.id p.user_id%}">
                                        {% csrf_token %}
                                        <button class="btn btn-primary" type='submit'>Acordar</button>
                                    </form>
                                </th>
                                {%endif%}

                                {%endif%}  
                                             
                            {%endif%}
                          </tr>
                          {%endfor%}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
            </div>
            
    
        </div>
        
      </div>
      <h3>{{error}}</h3>
</body>

<script type="text/javascript">
  function myFunction() {
    var a = "{{error}}";
    if(a > 0){
      alert("Ya te has postulado anteriormente");
    }
      
  }
</script>
  {% endblock %}

templates/users/publication_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>Desea eliminar el registro de {{publication.name}}</h3>
   <button type="submit">Si, eliminar</button>
   <a href="/users/publication_list/">Cancelar</a>
</form>
{% endblock%}